/**
 * Copyright 2005-2042, Stadt Bielefeld
 *
 * This file is part of AUIK (Anlagen- und Indirekteinleiter-Kataster).
 *
 * AUIK is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 2 of the License, or (at your
 * option) any later version.
 *
 * AUIK is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with AUIK. If not, see <http://www.gnu.org/licenses/>.
 *
 * AUIK has been developed by Stadt Bielefeld and Intevation GmbH.
 */

// Generated by Hibernate Tools 5.0.0.Final

package de.bielefeld.umweltamt.aui.mappings.oberflgw;

import de.bielefeld.umweltamt.aui.mappings.DatabaseAccess;
import de.bielefeld.umweltamt.aui.mappings.DatabaseQuery;
import de.bielefeld.umweltamt.aui.mappings.DatabaseSerialVersionUID;
import de.bielefeld.umweltamt.aui.mappings.atl.Messstelle;
import de.bielefeld.umweltamt.aui.utils.AuikLogger;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * A class that represents a row in the MsstBerichtspflicht database table.<br>
 * This class is meant to serve as a model and should be copied into the
 * appropriate package and may be customized below the given mark.
 */
public class MsstBerichtspflicht  implements java.io.Serializable {

    /** Generated serialVersionUID for Serializable interface */
    private static final long serialVersionUID =
        DatabaseSerialVersionUID.forMsstBerichtspflicht;

    /* Primary key, foreign keys (relations) and table columns */
    private Integer msstNr;
    private Integer origMsstNr;
    private Messstelle messstelle;
    private Integer berichtspflichtOpt;

    /** Logging */
    private static final AuikLogger log = AuikLogger.getLogger();

    /** Default constructor */
    public MsstBerichtspflicht() {
        // This place is intentionally left blank.
    }


    /** Full constructor */
    public MsstBerichtspflicht(
        Integer id, Messstelle messstelle, Integer berichtspflichtOpt) {
        this.msstNr = id;
        this.messstelle = messstelle;
        this.berichtspflichtOpt = berichtspflichtOpt;
    }

    /* Setter and getter methods */
    public Integer getMsstNr() {
        return this.msstNr;
    }

    public void setMsstNr(Integer id) {
        this.msstNr = id;
    }

    @JsonIgnore
    public Integer getOrigMsstNr() {
        return origMsstNr;
    }

    public void setOrigMsstNr(Integer origMsstNr) {
        this.origMsstNr = origMsstNr;
    }

    @JsonBackReference
    public Messstelle getMessstelle() {
        return this.messstelle;
    }

    public void setMessstelle(Messstelle messstelle) {
        this.messstelle = messstelle;
    }

    public Integer getBerichtspflichtOpt() {
        return this.berichtspflichtOpt;
    }

    public void setBerichtspflichtOpt(Integer berichtspflichtopt) {
        this.berichtspflichtOpt = berichtspflichtopt;
    }

    /**
     * To implement custom toString methods, jump to not generated code.<br>
     * Basically we either call on <code>toDebugString</code> for a debug
     * string, call on <code>toGuiString</code> for a gui representation or do
     * something completely different.
     * @return String
     */
    @Override
    public String toString() {
        return "";
    }

    /**
     * Get a string representation for debugging
     * @return String
     */
    public String toDebugString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getSimpleName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("messstelle").append("='").append(getMessstelle()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * @param other
     * @return <code>true</code>, if this and other are equal,
     *         <code>false</code> otherwise
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        if (other == null) return false;
        if (!(other instanceof MsstBerichtspflicht)) return false;
        return getMsstNr().equals(
            ((MsstBerichtspflicht)other).getMsstNr());
    }

    /**
     * Calculate a unique hashCode
     * @return <code>int</code>
     */
    @Override
    public int hashCode() {
        int result = 17;
        int idValue = this.getMsstNr() == null ?
            0 : this.getMsstNr().hashCode();
        result = result * 37 + idValue;
        return result;
    }

    /**
     * Merge (save or update) a detached instance
     * @param detachedInstance the instance to merge
     * @return <code>MsstBerichtspflicht</code> the merged instance,
     *         if everything went okay,
     *         <code>null</code> otherwise
     */
    public static MsstBerichtspflicht merge(MsstBerichtspflicht detachedInstance) {
        log.debug("Merging MsstBerichtspflicht instance " + detachedInstance);
        return (MsstBerichtspflicht) new DatabaseAccess().merge(detachedInstance);
    }

    /**
     * Merge (save or update) this instance
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public boolean merge() {
        MsstBerichtspflicht saved = MsstBerichtspflicht.merge(this);
        if (saved == null) {
            return false;
        } else {
            this.copy(saved);
            return true;
        }
    }

    /**
     * Update this MsstBerichtspflicht with its new values.<br>
     * This is meant to be used after merging!
     * @param copy MsstBerichtspflicht
     */
    private void copy(MsstBerichtspflicht copy) {
        this.msstNr = copy.getMsstNr();
        this.messstelle = copy.getMessstelle();
    }

    /**
     * Delete (mark as deleted) a detached instance
     * @param detachedInstance the instance to delete
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public static boolean delete(MsstBerichtspflicht detachedInstance) {
        log.debug("Deleting MsstBerichtspflicht instance " + detachedInstance);
        return new DatabaseAccess().delete(detachedInstance);
    }

    /**
     * Delete (mark as deleted) this instance
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public boolean delete() {
        return MsstBerichtspflicht.delete(this);
    }

    /**
     * Find an <code>MsstBerichtspflicht</code> instance by its primary key
     * @param id the primary key value
     * @return <code>MsstBerichtspflicht</code> the requested instance,
     *         if one exists,
     *         <code>null</code> otherwise
     */
    public static MsstBerichtspflicht findById(Integer id) {
        log.debug("Getting MsstBerichtspflicht instance with id: " + id);
        return (MsstBerichtspflicht)
            new DatabaseAccess().get(MsstBerichtspflicht.class, id);
    }

    /**
     * Get a list of all <code>MsstBerichtspflicht</code>
     * @return <code>List&lt;MsstBerichtspflicht&gt;</code>
     *         all <code>MsstBerichtspflicht</code>
     */
    public static List<MsstBerichtspflicht> getAll() {
        return DatabaseQuery.getAll(new MsstBerichtspflicht());
    }

    /* Custom code goes below here! */

}
