/**
 * Copyright 2005-2011, Stadt Bielefeld
 *
 * This file is part of AUIK (Anlagen- und Indirekteinleiter-Kataster).
 *
 * AUIK is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 2 of the License, or (at your
 * option) any later version.
 *
 * AUIK is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with AUIK. If not, see <http://www.gnu.org/licenses/>.
 *
 * AUIK has been developed by Stadt Bielefeld and Intevation GmbH.
 */
package de.bielefeld.umweltamt.aui.mappings.elka;

// Generated 22.10.2015 16:17:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import de.bielefeld.umweltamt.aui.mappings.DatabaseAccess;
import de.bielefeld.umweltamt.aui.mappings.DatabaseQuery;

/**
 * EWasserrecht generated by hbm2java
 */
public class EWasserrecht implements java.io.Serializable {

	private Integer nr;
	private Integer origNr;
	private EAdresse adresse;
	private Integer rechtArtOpt;
	private Date antragDat;
	private Date erteilungWrDat;
	private Boolean befristungTog;
	private Date befristungDat;
	private String bemerkung;
	private Date aktualDat;
	private Date erstellDat;
	private String aktenzeichen;
	private String herkunft;

	public EWasserrecht() {
	}

	public EWasserrecht(Integer nr) {
		this.nr = nr;
	}

	public EWasserrecht(Integer nr, Integer origNr, EAdresse adresse,
			Integer rechtArtOpt, Date antragDat, Date erteilungWrDat,
			Boolean befristungTog, Date befristungDat, String bemerkung,
			Date aktualDat, Date erstellDat, String aktenzeichen,
			String herkunft) {
		this.nr = nr;
		this.origNr = origNr;
		this.adresse = adresse;
		this.rechtArtOpt = rechtArtOpt;
		this.antragDat = antragDat;
		this.erteilungWrDat = erteilungWrDat;
		this.befristungTog = befristungTog;
		this.befristungDat = befristungDat;
		this.bemerkung = bemerkung;
		this.aktualDat = aktualDat;
		this.erstellDat = erstellDat;
		this.setAktenzeichen(aktenzeichen);
		this.herkunft = herkunft;
	}

	public Integer getNr() {
		return this.nr;
	}

	public void setNr(Integer nr) {
		this.nr = nr;
	}
	
	@JsonIgnore
	public Integer getOrigNr() {
		return this.origNr;
	}
	
	@JsonIgnore
	public void setOrigNr(Integer origNr) {
		this.origNr = origNr;
	}

	public EAdresse getAdresse() {
		return this.adresse;
	}

	public void setAdresse(EAdresse adresse) {
		this.adresse = adresse;
	}

	public Integer getRechtArtOpt() {
		return this.rechtArtOpt;
	}

	public void setRechtArtOpt(Integer rechtArtOpt) {
		this.rechtArtOpt = rechtArtOpt;
	}

	public Date getAntragDat() {
		return this.antragDat;
	}

	public void setAntragDat(Date antragDat) {
		this.antragDat = antragDat;
	}

	public Date getErteilungWrDat() {
		return this.erteilungWrDat;
	}

	public void setErteilungWrDat(Date erteilungWrDat) {
		this.erteilungWrDat = erteilungWrDat;
	}

	public Boolean getBefristungTog() {
		return this.befristungTog;
	}

	public void setBefristungTog(Boolean befristungTog) {
		this.befristungTog = befristungTog;
	}

	public Date getBefristungDat() {
		return this.befristungDat;
	}

	public void setBefristungDat(Date befristungDat) {
		this.befristungDat = befristungDat;
	}

	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	public Date getAktualDat() {
		return this.aktualDat;
	}

	public void setAktualDat(Date aktualDat) {
		this.aktualDat = aktualDat;
	}

	public Date getErstellDat() {
		return this.erstellDat;
	}

	public void setErstellDat(Date erstellDat) {
		this.erstellDat = erstellDat;
	}

	public String getHerkunft() {
		return this.herkunft;
	}

	public void setHerkunft(String herkunft) {
		this.herkunft = herkunft;
	}

    /**
     * Update this EAbwasserbehandlungsanlage with its new values.<br>
     * This is meant to be used after merging!
     * @param copy AtlKlaeranlagen
     */
    private void copy(EWasserrecht copy) {
    	this.adresse = copy.getAdresse();
    	this.antragDat = copy.getAntragDat();
    	this.befristungDat = copy.getBefristungDat();
    	this.befristungTog = copy.getBefristungTog();
    	this.bemerkung = copy.getBemerkung();
    	this.erteilungWrDat = copy.getErteilungWrDat();
    	this.nr = copy.getNr();
    	this.rechtArtOpt = copy.getRechtArtOpt();
    	this.aktualDat = copy.getAktualDat();
    	this.erstellDat = copy.getErstellDat();
    	this.herkunft = copy.getHerkunft();
    }

    /**
     * Find an {@link EWasserrecht} instance by its primary key
     * @param id the primary key value
     * @return {@link EWasserrecht} the requested instance,
     *         if one exists,
     *         <code>null</code> otherwise
     */
    public static EWasserrecht findById(java.lang.Integer id) {
        return (EWasserrecht)
            new DatabaseAccess().get(EWasserrecht.class, id);
    }

    /**
     * Get a list of all {@link EWasserrecht}
     * @return <code>List&lt;EWasserrecht&gt;</code>
     *         all {@link EWasserrecht}
     */
    public static List<EWasserrecht> getAll() {
        return DatabaseQuery.getAll(new EWasserrecht());
    }

	public String getAktenzeichen() {
		return aktenzeichen;
	}

	public void setAktenzeichen(String aktenzeichen) {
		this.aktenzeichen = aktenzeichen;
	}
}
