/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Jan 20 17:02:28 CET 2005 by MyEclipse Hibernate Tool.
 */
package de.bielefeld.umweltamt.aui.mappings.basis;

import java.io.Serializable;

/**
 * A class that represents a row in the BASIS_GEMARKUNG table.
 * You can customize the behavior of this class by editing the class, {@link BasisGemarkung}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractBasisGemarkung
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer gemarkungid;

    /** The value of the simple gemarkung property. */
    private java.lang.String gemarkung;

    /**
     * Simple constructor of AbstractBasisGemarkung instances.
     */
    public AbstractBasisGemarkung()
    {
    }

    /**
     * Constructor of AbstractBasisGemarkung instances given a simple primary key.
     * @param gemarkungid
     */
    public AbstractBasisGemarkung(java.lang.Integer gemarkungid)
    {
        this.setGemarkungid(gemarkungid);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getGemarkungid()
    {
        return gemarkungid;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param gemarkungid
     */
    public void setGemarkungid(java.lang.Integer gemarkungid)
    {
        this.hashValue = 0;
        this.gemarkungid = gemarkungid;
    }

    /**
     * Return the value of the GEMARKUNG column.
     * @return java.lang.String
     */
    public java.lang.String getGemarkung()
    {
        return this.gemarkung;
    }

    /**
     * Set the value of the GEMARKUNG column.
     * @param gemarkung
     */
    public void setGemarkung(java.lang.String gemarkung)
    {
        this.gemarkung = gemarkung;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof BasisGemarkung))
            return false;
        BasisGemarkung that = (BasisGemarkung) rhs;
        if (this.getGemarkungid() != null && that.getGemarkungid() != null)
        {
            if (! this.getGemarkungid().equals(that.getGemarkungid()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int gemarkungidValue = this.getGemarkungid() == null ? 0 : this.getGemarkungid().hashCode();
            result = result * 37 + gemarkungidValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
