/**
 * Copyright 2005-2042, Stadt Bielefeld
 *
 * This file is part of AUIK (Anlagen- und Indirekteinleiter-Kataster).
 *
 * AUIK is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 2 of the License, or (at your
 * option) any later version.
 *
 * AUIK is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with AUIK. If not, see <http://www.gnu.org/licenses/>.
 *
 * AUIK has been developed by Stadt Bielefeld and Intevation GmbH.
 */

// Generated by Hibernate Tools 3.3.0.GA

package de.bielefeld.umweltamt.aui.mappings.basis;

import java.util.Date;
import java.util.List;

import de.bielefeld.umweltamt.aui.mappings.DatabaseAccess;
import de.bielefeld.umweltamt.aui.mappings.DatabaseClassToString;
import de.bielefeld.umweltamt.aui.mappings.DatabaseQuery;
import de.bielefeld.umweltamt.aui.mappings.DatabaseSerialVersionUID;
import de.bielefeld.umweltamt.aui.utils.AuikLogger;

/**
 * A class that represents a row in the BasisObjektchrono database table.<br>
 * This class is meant to serve as a model and should be copied into the
 * appropriate package and may be customized below the given mark.
 */
public class BasisObjektchrono  implements java.io.Serializable {

    /** Generated serialVersionUID for Serializable interface */
    private static final long serialVersionUID =
        DatabaseSerialVersionUID.forBasisObjektchrono;

    /* Primary key, foreign keys (relations) and table columns */
    private Integer id;
    private BasisObjekt basisObjekt;
    private Date datum;
    private String sachverhalt;
    private Date wv;
    private String sachbearbeiter;
    private boolean enabled;
    private boolean deleted;

    /** Logging */
    private static final AuikLogger log = AuikLogger.getLogger();

    /** Default constructor */
    public BasisObjektchrono() {
        // This place is intentionally left blank.
    }

    /** Minimal constructor */
    public BasisObjektchrono(
        boolean enabled, boolean deleted) {
        this.enabled = enabled;
        this.deleted = deleted;
    }

    /** Full constructor */
    public BasisObjektchrono(
        BasisObjekt basisObjekt, Date datum, String sachverhalt, Date wv, String sachbearbeiter, boolean enabled, boolean deleted) {
        this.basisObjekt = basisObjekt;
        this.datum = datum;
        this.sachverhalt = sachverhalt;
        this.wv = wv;
        this.sachbearbeiter = sachbearbeiter;
        this.enabled = enabled;
        this.deleted = deleted;
    }

    /* Setter and getter methods */
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public BasisObjekt getBasisObjekt() {
        return this.basisObjekt;
    }

    public void setBasisObjekt(BasisObjekt basisObjekt) {
        this.basisObjekt = basisObjekt;
    }

    public Date getDatum() {
        return this.datum;
    }

    public void setDatum(Date datum) {
        this.datum = datum;
    }

    public String getSachverhalt() {
        return this.sachverhalt;
    }

    public void setSachverhalt(String sachverhalt) {
        this.sachverhalt = sachverhalt;
    }

    public Date getWv() {
        return this.wv;
    }

    public void setWv(Date wv) {
        this.wv = wv;
    }

    public String getSachbearbeiter() {
        return this.sachbearbeiter;
    }

    public void setSachbearbeiter(String sachbearbeiter) {
        this.sachbearbeiter = sachbearbeiter;
    }

    public boolean isEnabled() {
        return this.enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * To implement custom toString methods, jump to not generated code.<br>
     * Basically we either call on <code>toDebugString</code> for a debug
     * string, call on <code>toGuiString</code> for a gui representation or do
     * something completely different.
     * @return String
     */
    @Override
    public String toString() {
        return DatabaseClassToString.toStringForClass(this);
    }

    /**
     * Get a string representation for debugging
     * @return String
     */
    public String toDebugString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getSimpleName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("basisObjekt").append("='").append(getBasisObjekt()).append("' ");
        buffer.append("datum").append("='").append(getDatum()).append("' ");
        buffer.append("sachverhalt").append("='").append(getSachverhalt()).append("' ");
        buffer.append("wv").append("='").append(getWv()).append("' ");
        buffer.append("sachbearbeiter").append("='").append(getSachbearbeiter()).append("' ");
        buffer.append("enabled").append("='").append(isEnabled()).append("' ");
        buffer.append("deleted").append("='").append(isDeleted()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * @param other
     * @return <code>true</code>, if this and other are equal,
     *         <code>false</code> otherwise
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        if (other == null) return false;
        if (!(other instanceof BasisObjektchrono)) return false;
        return (this.getId().equals(
            ((BasisObjektchrono) other).getId()));
    }

    /**
     * Merge (save or update) a detached instance
     * @param detachedInstance the instance to merge
     * @return <code>BasisObjektchrono</code> the merged instance,
     *         if everything went okay,
     *         <code>null</code> otherwise
     */
    public static BasisObjektchrono merge(BasisObjektchrono detachedInstance) {
        log.debug("Merging BasisObjektchrono instance " + detachedInstance);
        return (BasisObjektchrono) new DatabaseAccess().merge(detachedInstance);
    }

    /**
     * Merge (save or update) this instance
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public boolean merge() {
        return BasisObjektchrono.merge(this).equals(this);
    }

    /**
     * Delete (mark as deleted) a detached instance
     * @param detachedInstance the instance to delete
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public static boolean delete(BasisObjektchrono detachedInstance) {
        log.debug("Deleting BasisObjektchrono instance " + detachedInstance);
        return new DatabaseAccess().delete(detachedInstance);
    }

    /**
     * Delete (mark as deleted) this instance
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public boolean delete() {
        return BasisObjektchrono.delete(this);
    }

    /**
     * Find an <code>BasisObjektchrono</code> instance by its primary key
     * @param id the primary key value
     * @return <code>BasisObjektchrono</code> the requested instance,
     *         if one exists,
     *         <code>null</code> otherwise
     */
    public static BasisObjektchrono findById(java.lang.Integer id) {
        log.debug("Getting BasisObjektchrono instance with id: " + id);
        return (BasisObjektchrono)
            new DatabaseAccess().get(BasisObjektchrono.class, id);
    }

    /**
     * Get a list of all <code>BasisObjektchrono</code>
     * @return <code>List&lt;BasisObjektchrono&gt;</code>
     *         all <code>BasisObjektchrono</code>
     */
    public static List<BasisObjektchrono> getAll() {
        return DatabaseQuery.getAll(new BasisObjektchrono());
    }

    /* Custom code goes below here! */

}
