/**
 * Copyright 2005-2042, Stadt Bielefeld
 *
 * This file is part of AUIK (Anlagen- und Indirekteinleiter-Kataster).
 *
 * AUIK is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 2 of the License, or (at your
 * option) any later version.
 *
 * AUIK is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with AUIK. If not, see <http://www.gnu.org/licenses/>.
 *
 * AUIK has been developed by Stadt Bielefeld and Intevation GmbH.
 */

// Generated by Hibernate Tools 5.0.0.Final

package de.bielefeld.umweltamt.aui.mappings.basis;

import de.bielefeld.umweltamt.aui.mappings.DatabaseAccess;
import de.bielefeld.umweltamt.aui.mappings.DatabaseClassToString;
import de.bielefeld.umweltamt.aui.mappings.DatabaseQuery;
import de.bielefeld.umweltamt.aui.mappings.DatabaseSerialVersionUID;
import de.bielefeld.umweltamt.aui.utils.AuikLogger;
import java.util.List;

/**
 * A class that represents a row in the MapAdresseLage database table.<br>
 * This class is meant to serve as a model and should be copied into the
 * appropriate package and may be customized below the given mark.
 */
public class MapAdresseLage  implements java.io.Serializable {

    /** Generated serialVersionUID for Serializable interface */
    private static final long serialVersionUID =
        DatabaseSerialVersionUID.forMapAdresseLage;
    
    /* Primary key, foreign keys (relations) and table columns */
    private Integer id;
    private Integer adresseid;
    private Integer lageid;
    private Boolean enabled;
    private Boolean deleted;

    /** Logging */
    private static final AuikLogger log = AuikLogger.getLogger();

    /** Default constructor */
    public MapAdresseLage() {
        // This place is intentionally left blank.
    }

    /** Minimal constructor */
    public MapAdresseLage(
        Integer id) {
        this.id = id;
    }

    /** Full constructor */
    public MapAdresseLage(
        Integer id, Integer adresseid, Integer lageid, Boolean enabled, Boolean deleted) {
        this.id = id;
        this.adresseid = adresseid;
        this.lageid = lageid;
        this.enabled = enabled;
        this.deleted = deleted;
    }

    /* Setter and getter methods */
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getAdresseid() {
        return this.adresseid;
    }

    public void setAdresseid(Integer adresseid) {
        this.adresseid = adresseid;
    }

    public Integer getLageid() {
        return this.lageid;
    }

    public void setLageid(Integer lageid) {
        this.lageid = lageid;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Boolean getDeleted() {
        return this.deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * To implement custom toString methods, jump to not generated code.<br>
     * Basically we either call on <code>toDebugString</code> for a debug
     * string, call on <code>toGuiString</code> for a gui representation or do
     * something completely different.
     * @return String
     */
    @Override
    public String toString() {
        return DatabaseClassToString.toStringForClass(this); 
    }

    /**
     * Get a string representation for debugging
     * @return String
     */
    public String toDebugString() {
        StringBuffer buffer = new StringBuffer();
        
        buffer.append(getClass().getSimpleName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");			
        buffer.append("adresseid").append("='").append(getAdresseid()).append("' ");			
        buffer.append("lageid").append("='").append(getLageid()).append("' ");			
        buffer.append("enabled").append("='").append(getEnabled()).append("' ");			
        buffer.append("deleted").append("='").append(getDeleted()).append("' ");			
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * @param other
     * @return <code>true</code>, if this and other are equal,
     *         <code>false</code> otherwise
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        if (other == null) return false;
        if (!(other instanceof MapAdresseLage)) return false;
        return (this.getId().equals(
            ((MapAdresseLage) other).getId()));
    }

    /**
     * Calculate a unique hashCode
     * @return <code>int</code>
     */
    @Override
    public int hashCode() {
        int result = 17;
        int idValue = this.getId() == null ?
            0 : this.getId().hashCode();
        result = result * 37 + idValue;
        return result;
    }
    
    /**
     * Merge (save or update) a detached instance
     * @param detachedInstance the instance to merge
     * @return <code>MapAdresseLage</code> the merged instance,
     *         if everything went okay,
     *         <code>null</code> otherwise
     */
    public static MapAdresseLage merge(MapAdresseLage detachedInstance) {
        log.debug("Merging MapAdresseLage instance " + detachedInstance);
        return (MapAdresseLage) new DatabaseAccess().merge(detachedInstance);
    }

    /**
     * Merge (save or update) this instance
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public boolean merge() {
        MapAdresseLage saved = MapAdresseLage.merge(this);
        if (saved == null) {
            return false;
        } else {
            this.copy(saved);
            return true;
        }
    }

    /**
     * Update this MapAdresseLage with its new values.<br>
     * This is meant to be used after merging!
     * @param copy MapAdresseLage
     */
    private void copy(MapAdresseLage copy) {
        this.id = copy.getId();            
        this.adresseid = copy.getAdresseid();            
        this.lageid = copy.getLageid();            
        this.enabled = copy.getEnabled();            
        this.deleted = copy.getDeleted();            
    }    

    /**
     * Delete (mark as deleted) a detached instance
     * @param detachedInstance the instance to delete
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public static boolean delete(MapAdresseLage detachedInstance) {
        log.debug("Deleting MapAdresseLage instance " + detachedInstance);
        return new DatabaseAccess().delete(detachedInstance);
    }

    /**
     * Delete (mark as deleted) this instance
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public boolean delete() {
        return MapAdresseLage.delete(this);
    }

    /**
     * Find an <code>MapAdresseLage</code> instance by its primary key
     * @param id the primary key value
     * @return <code>MapAdresseLage</code> the requested instance,
     *         if one exists,
     *         <code>null</code> otherwise
     */
    public static MapAdresseLage findById(java.lang.Integer id) {
        log.debug("Getting MapAdresseLage instance with id: " + id);
        return (MapAdresseLage)
            new DatabaseAccess().get(MapAdresseLage.class, id);
    }

    /**
     * Get a list of all <code>MapAdresseLage</code>
     * @return <code>List&lt;MapAdresseLage&gt;</code>
     *         all <code>MapAdresseLage</code>
     */
    public static List<MapAdresseLage> getAll() {
        return DatabaseQuery.getAll(new MapAdresseLage());
    }

    /* Custom code goes below here! */

}
