/**
 * Copyright 2005-2042, Stadt Bielefeld
 *
 * This file is part of AUIK (Anlagen- und Indirekteinleiter-Kataster).
 *
 * AUIK is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 2 of the License, or (at your
 * option) any later version.
 *
 * AUIK is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with AUIK. If not, see <http://www.gnu.org/licenses/>.
 *
 * AUIK has been developed by Stadt Bielefeld and Intevation GmbH.
 */

// Generated by Hibernate Tools 5.0.0.Final

package de.bielefeld.umweltamt.aui.mappings.basis;

import de.bielefeld.umweltamt.aui.mappings.DatabaseClassToString;
import de.bielefeld.umweltamt.aui.mappings.DatabaseSerialVersionUID;

/**
 * A class that represents a row in the ViewTwoWayObjektverknuepfungId database table.<br>
 * This class is meant to serve as a model and should be copied into the
 * appropriate package and may be customized below the given mark.
 */
public class ViewTwoWayObjektverknuepfungId  implements java.io.Serializable {

    /** Generated serialVersionUID for Serializable interface */
    private static final long serialVersionUID =
        DatabaseSerialVersionUID.forViewTwoWayObjektverknuepfungId;

    /* Primary key, foreign keys (relations) and table columns */
    private Integer id;
    private Integer istVerknuepftMit;
    private Integer objekt;
    private Boolean enabled;
    private Boolean deleted;

    /** Default constructor */
    public ViewTwoWayObjektverknuepfungId() {
        // This place is intentionally left blank.
    }


    /** Full constructor */
    public ViewTwoWayObjektverknuepfungId(
        Integer id, Integer istVerknuepftMit, Integer objekt, Boolean enabled, Boolean deleted) {
        this.id = id;
        this.istVerknuepftMit = istVerknuepftMit;
        this.objekt = objekt;
        this.enabled = enabled;
        this.deleted = deleted;
    }

    /* Setter and getter methods */
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIstVerknuepftMit() {
        return this.istVerknuepftMit;
    }

    public void setIstVerknuepftMit(Integer istVerknuepftMit) {
        this.istVerknuepftMit = istVerknuepftMit;
    }

    public Integer getObjekt() {
        return this.objekt;
    }

    public void setObjekt(Integer objekt) {
        this.objekt = objekt;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Boolean getDeleted() {
        return this.deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * To implement custom toString methods, jump to not generated code.<br>
     * Basically we either call on <code>toDebugString</code> for a debug
     * string, call on <code>toGuiString</code> for a gui representation or do
     * something completely different.
     * @return String
     */
    @Override
    public String toString() {
        return DatabaseClassToString.toStringForClass(this);
    }

    /**
     * Get a string representation for debugging
     * @return String
     */
    public String toDebugString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getSimpleName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("id").append("='").append(getId()).append("' ");
        buffer.append("istVerknuepftMit").append("='").append(getIstVerknuepftMit()).append("' ");
        buffer.append("objekt").append("='").append(getObjekt()).append("' ");
        buffer.append("enabled").append("='").append(getEnabled()).append("' ");
        buffer.append("deleted").append("='").append(getDeleted()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /* Custom code goes below here! */

}
