<#include "AuikCopyright.ftl"/>

// Generated by Hibernate Tools ${version}

${pojo.getPackageDeclaration()}
<#assign classbody>
<#include "AuikPojoTypeDeclaration.ftl"/> {

<#if !pojo.isInterface()>
<#include "AuikPojoFields.ftl"/>
<#include "AuikPojoConstructors.ftl"/>
<#include "AuikPojoPropertyAccessors.ftl"/>
<#include "PojoToString.ftl"/>
<#include "PojoEqualsHashcode.ftl"/>
<#else>
<#include "PojoInterfacePropertyAccessors.ftl"/>
</#if>
<#include "PojoExtraClassCode.ftl"/>
}
</#assign>

${pojo.generateImports()}
${classbody}
