/**
 * Copyright 2005-2042, Stadt Bielefeld
 *
 * This file is part of AUIK (Anlagen- und Indirekteinleiter-Kataster).
 *
 * AUIK is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 2 of the License, or (at your
 * option) any later version.
 *
 * AUIK is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with AUIK. If not, see <http://www.gnu.org/licenses/>.
 *
 * AUIK has been developed by Stadt Bielefeld and Intevation GmbH.
 */

// Generated by Hibernate Tools 3.3.0.GA

package de.bielefeld.umweltamt.aui.mappings.indeinl;

import java.util.Date;
import java.util.List;

import de.bielefeld.umweltamt.aui.mappings.DatabaseAccess;
import de.bielefeld.umweltamt.aui.mappings.DatabaseClassToString;
import de.bielefeld.umweltamt.aui.mappings.DatabaseQuery;
import de.bielefeld.umweltamt.aui.mappings.DatabaseSerialVersionUID;
import de.bielefeld.umweltamt.aui.utils.AuikLogger;

/**
 * A class that represents a row in the Anh49Analysen database table.<br>
 * This class is meant to serve as a model and should be copied into the
 * appropriate package and may be customized below the given mark.
 */
public class Anh49Analysen  implements java.io.Serializable {

    /** Generated serialVersionUID for Serializable interface */
    private static final long serialVersionUID =
        DatabaseSerialVersionUID.forAnh49Analysen;

    /* Primary key, foreign keys (relations) and table columns */
    private Integer id;
    private Anh49Fachdaten anh49Fachdaten;
    private Date datum;
    private String institut;
    private String csbWert;
    private String csbGrenzwert;
    private String aoxWert;
    private String aoxGrenzwert;
    private String kwWert;
    private String kwGrenzwert;
    private String zinkWert;
    private String zinkGrenzwert;
    private String bsb5Wert;
    private String bsb5CsbRelation;
    private String bemerkungen;
    private String bikGrenzwert;
    private String bikWert;
    private String phWert;
    private String phGrenzwert;
    private boolean enabled;
    private boolean deleted;

    /** Logging */
    private static final AuikLogger log = AuikLogger.getLogger();

    /** Default constructor */
    public Anh49Analysen() {
        // This place is intentionally left blank.
    }

    /** Minimal constructor */
    public Anh49Analysen(
        boolean enabled, boolean deleted) {
        this.enabled = enabled;
        this.deleted = deleted;
    }

    /** Full constructor */
    public Anh49Analysen(
        Anh49Fachdaten anh49Fachdaten, Date datum, String institut, String csbWert, String csbGrenzwert, String aoxWert, String aoxGrenzwert, String kwWert, String kwGrenzwert, String zinkWert, String zinkGrenzwert, String bsb5Wert, String bsb5CsbRelation, String bemerkungen, String bikGrenzwert, String bikWert, String phWert, String phGrenzwert, boolean enabled, boolean deleted) {
        this.anh49Fachdaten = anh49Fachdaten;
        this.datum = datum;
        this.institut = institut;
        this.csbWert = csbWert;
        this.csbGrenzwert = csbGrenzwert;
        this.aoxWert = aoxWert;
        this.aoxGrenzwert = aoxGrenzwert;
        this.kwWert = kwWert;
        this.kwGrenzwert = kwGrenzwert;
        this.zinkWert = zinkWert;
        this.zinkGrenzwert = zinkGrenzwert;
        this.bsb5Wert = bsb5Wert;
        this.bsb5CsbRelation = bsb5CsbRelation;
        this.bemerkungen = bemerkungen;
        this.bikGrenzwert = bikGrenzwert;
        this.bikWert = bikWert;
        this.phWert = phWert;
        this.phGrenzwert = phGrenzwert;
        this.enabled = enabled;
        this.deleted = deleted;
    }

    /* Setter and getter methods */
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Anh49Fachdaten getAnh49Fachdaten() {
        return this.anh49Fachdaten;
    }

    public void setAnh49Fachdaten(Anh49Fachdaten anh49Fachdaten) {
        this.anh49Fachdaten = anh49Fachdaten;
    }

    public Date getDatum() {
        return this.datum;
    }

    public void setDatum(Date datum) {
        this.datum = datum;
    }

    public String getInstitut() {
        return this.institut;
    }

    public void setInstitut(String institut) {
        this.institut = institut;
    }

    public String getCsbWert() {
        return this.csbWert;
    }

    public void setCsbWert(String csbWert) {
        this.csbWert = csbWert;
    }

    public String getCsbGrenzwert() {
        return this.csbGrenzwert;
    }

    public void setCsbGrenzwert(String csbGrenzwert) {
        this.csbGrenzwert = csbGrenzwert;
    }

    public String getAoxWert() {
        return this.aoxWert;
    }

    public void setAoxWert(String aoxWert) {
        this.aoxWert = aoxWert;
    }

    public String getAoxGrenzwert() {
        return this.aoxGrenzwert;
    }

    public void setAoxGrenzwert(String aoxGrenzwert) {
        this.aoxGrenzwert = aoxGrenzwert;
    }

    public String getKwWert() {
        return this.kwWert;
    }

    public void setKwWert(String kwWert) {
        this.kwWert = kwWert;
    }

    public String getKwGrenzwert() {
        return this.kwGrenzwert;
    }

    public void setKwGrenzwert(String kwGrenzwert) {
        this.kwGrenzwert = kwGrenzwert;
    }

    public String getZinkWert() {
        return this.zinkWert;
    }

    public void setZinkWert(String zinkWert) {
        this.zinkWert = zinkWert;
    }

    public String getZinkGrenzwert() {
        return this.zinkGrenzwert;
    }

    public void setZinkGrenzwert(String zinkGrenzwert) {
        this.zinkGrenzwert = zinkGrenzwert;
    }

    public String getBsb5Wert() {
        return this.bsb5Wert;
    }

    public void setBsb5Wert(String bsb5Wert) {
        this.bsb5Wert = bsb5Wert;
    }

    public String getBsb5CsbRelation() {
        return this.bsb5CsbRelation;
    }

    public void setBsb5CsbRelation(String bsb5CsbRelation) {
        this.bsb5CsbRelation = bsb5CsbRelation;
    }

    public String getBemerkungen() {
        return this.bemerkungen;
    }

    public void setBemerkungen(String bemerkungen) {
        this.bemerkungen = bemerkungen;
    }

    public String getBikGrenzwert() {
        return this.bikGrenzwert;
    }

    public void setBikGrenzwert(String bikGrenzwert) {
        this.bikGrenzwert = bikGrenzwert;
    }

    public String getBikWert() {
        return this.bikWert;
    }

    public void setBikWert(String bikWert) {
        this.bikWert = bikWert;
    }

    public String getPhWert() {
        return this.phWert;
    }

    public void setPhWert(String phWert) {
        this.phWert = phWert;
    }

    public String getPhGrenzwert() {
        return this.phGrenzwert;
    }

    public void setPhGrenzwert(String phGrenzwert) {
        this.phGrenzwert = phGrenzwert;
    }

    public boolean isEnabled() {
        return this.enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * To implement custom toString methods, jump to not generated code.<br>
     * Basically we either call on <code>toDebugString</code> for a debug
     * string, call on <code>toGuiString</code> for a gui representation or do
     * something completely different.
     * @return String
     */
    @Override
    public String toString() {
        return DatabaseClassToString.toStringForClass(this);
    }

    /**
     * Get a string representation for debugging
     * @return String
     */
    public String toDebugString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getSimpleName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("anh49Fachdaten").append("='").append(getAnh49Fachdaten()).append("' ");
        buffer.append("datum").append("='").append(getDatum()).append("' ");
        buffer.append("institut").append("='").append(getInstitut()).append("' ");
        buffer.append("csbWert").append("='").append(getCsbWert()).append("' ");
        buffer.append("csbGrenzwert").append("='").append(getCsbGrenzwert()).append("' ");
        buffer.append("aoxWert").append("='").append(getAoxWert()).append("' ");
        buffer.append("aoxGrenzwert").append("='").append(getAoxGrenzwert()).append("' ");
        buffer.append("kwWert").append("='").append(getKwWert()).append("' ");
        buffer.append("kwGrenzwert").append("='").append(getKwGrenzwert()).append("' ");
        buffer.append("zinkWert").append("='").append(getZinkWert()).append("' ");
        buffer.append("zinkGrenzwert").append("='").append(getZinkGrenzwert()).append("' ");
        buffer.append("bsb5Wert").append("='").append(getBsb5Wert()).append("' ");
        buffer.append("bsb5CsbRelation").append("='").append(getBsb5CsbRelation()).append("' ");
        buffer.append("bemerkungen").append("='").append(getBemerkungen()).append("' ");
        buffer.append("bikGrenzwert").append("='").append(getBikGrenzwert()).append("' ");
        buffer.append("bikWert").append("='").append(getBikWert()).append("' ");
        buffer.append("phWert").append("='").append(getPhWert()).append("' ");
        buffer.append("phGrenzwert").append("='").append(getPhGrenzwert()).append("' ");
        buffer.append("enabled").append("='").append(isEnabled()).append("' ");
        buffer.append("deleted").append("='").append(isDeleted()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * @param other
     * @return <code>true</code>, if this and other are equal,
     *         <code>false</code> otherwise
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        if (other == null) return false;
        if (!(other instanceof Anh49Analysen)) return false;
        return (this.getId().equals(
            ((Anh49Analysen) other).getId()));
    }

    /**
     * Calculate a unique hashCode
     * @return <code>int</code>
     */
    @Override
    public int hashCode() {
        int result = 17;
        int idValue = this.getId() == null ?
            0 : this.getId().hashCode();
        result = result * 37 + idValue;
        return result;
    }

    /**
     * Merge (save or update) a detached instance
     * @param detachedInstance the instance to merge
     * @return <code>Anh49Analysen</code> the merged instance,
     *         if everything went okay,
     *         <code>null</code> otherwise
     */
    public static Anh49Analysen merge(Anh49Analysen detachedInstance) {
        log.debug("Merging Anh49Analysen instance " + detachedInstance);
        return (Anh49Analysen) new DatabaseAccess().merge(detachedInstance);
    }

    /**
     * Merge (save or update) this instance
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public boolean merge() {
        Anh49Analysen saved = Anh49Analysen.merge(this);
        if (saved == null) {
            return false;
        } else {
            this.copy(saved);
            return true;
        }
    }

    /**
     * Update this Anh49Analysen with its new values.<br>
     * This is meant to be used after merging!
     * @param copy Anh49Analysen
     */
    private void copy(Anh49Analysen copy) {
        this.anh49Fachdaten = copy.getAnh49Fachdaten();
        this.datum = copy.getDatum();
        this.institut = copy.getInstitut();
        this.csbWert = copy.getCsbWert();
        this.csbGrenzwert = copy.getCsbGrenzwert();
        this.aoxWert = copy.getAoxWert();
        this.aoxGrenzwert = copy.getAoxGrenzwert();
        this.kwWert = copy.getKwWert();
        this.kwGrenzwert = copy.getKwGrenzwert();
        this.zinkWert = copy.getZinkWert();
        this.zinkGrenzwert = copy.getZinkGrenzwert();
        this.bsb5Wert = copy.getBsb5Wert();
        this.bsb5CsbRelation = copy.getBsb5CsbRelation();
        this.bemerkungen = copy.getBemerkungen();
        this.bikGrenzwert = copy.getBikGrenzwert();
        this.bikWert = copy.getBikWert();
        this.phWert = copy.getPhWert();
        this.phGrenzwert = copy.getPhGrenzwert();
        this.enabled = copy.isEnabled();
        this.deleted = copy.isDeleted();
    }

    /**
     * Delete (mark as deleted) a detached instance
     * @param detachedInstance the instance to delete
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public static boolean delete(Anh49Analysen detachedInstance) {
        log.debug("Deleting Anh49Analysen instance " + detachedInstance);
        return new DatabaseAccess().delete(detachedInstance);
    }

    /**
     * Delete (mark as deleted) this instance
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public boolean delete() {
        return Anh49Analysen.delete(this);
    }

    /**
     * Find an <code>Anh49Analysen</code> instance by its primary key
     * @param id the primary key value
     * @return <code>Anh49Analysen</code> the requested instance,
     *         if one exists,
     *         <code>null</code> otherwise
     */
    public static Anh49Analysen findById(java.lang.Integer id) {
        log.debug("Getting Anh49Analysen instance with id: " + id);
        return (Anh49Analysen)
            new DatabaseAccess().get(Anh49Analysen.class, id);
    }

    /**
     * Get a list of all <code>Anh49Analysen</code>
     * @return <code>List&lt;Anh49Analysen&gt;</code>
     *         all <code>Anh49Analysen</code>
     */
    public static List<Anh49Analysen> getAll() {
        return DatabaseQuery.getAll(new Anh49Analysen());
    }

    /* Custom code goes below here! */

}
