/**
 * Copyright 2005-2042, Stadt Bielefeld
 *
 * This file is part of AUIK (Anlagen- und Indirekteinleiter-Kataster).
 *
 * AUIK is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 2 of the License, or (at your
 * option) any later version.
 *
 * AUIK is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with AUIK. If not, see <http://www.gnu.org/licenses/>.
 *
 * AUIK has been developed by Stadt Bielefeld and Intevation GmbH.
 */

// Generated by Hibernate Tools 3.3.0.GA

package de.bielefeld.umweltamt.aui.mappings.indeinl;

import java.util.Date;
import java.util.List;

import de.bielefeld.umweltamt.aui.mappings.DatabaseAccess;
import de.bielefeld.umweltamt.aui.mappings.DatabaseClassToString;
import de.bielefeld.umweltamt.aui.mappings.DatabaseQuery;
import de.bielefeld.umweltamt.aui.mappings.DatabaseSerialVersionUID;
import de.bielefeld.umweltamt.aui.utils.AuikLogger;

/**
 * A class that represents a row in the Anh49Verwaltungsverf database table.<br>
 * This class is meant to serve as a model and should be copied into the
 * appropriate package and may be customized below the given mark.
 */
public class Anh49Verwaltungsverf  implements java.io.Serializable {

    /** Generated serialVersionUID for Serializable interface */
    private static final long serialVersionUID =
        DatabaseSerialVersionUID.forAnh49Verwaltungsverf;

    /* Primary key, foreign keys (relations) and table columns */
    private Integer id;
    private Anh49Fachdaten anh49Fachdaten;
    private Date datum;
    private String massnahme;
    private String sachbearbeiterIn;
    private Date wiedervorlage;
    private Boolean abgeschlossen;
    private boolean enabled;
    private boolean deleted;

    /** Logging */
    private static final AuikLogger log = AuikLogger.getLogger();

    /** Default constructor */
    public Anh49Verwaltungsverf() {
        // This place is intentionally left blank.
    }

    /** Minimal constructor */
    public Anh49Verwaltungsverf(
        boolean enabled, boolean deleted) {
        this.enabled = enabled;
        this.deleted = deleted;
    }

    /** Full constructor */
    public Anh49Verwaltungsverf(
        Anh49Fachdaten anh49Fachdaten, Date datum, String massnahme, String sachbearbeiterIn, Date wiedervorlage, Boolean abgeschlossen, boolean enabled, boolean deleted) {
        this.anh49Fachdaten = anh49Fachdaten;
        this.datum = datum;
        this.massnahme = massnahme;
        this.sachbearbeiterIn = sachbearbeiterIn;
        this.wiedervorlage = wiedervorlage;
        this.abgeschlossen = abgeschlossen;
        this.enabled = enabled;
        this.deleted = deleted;
    }

    /* Setter and getter methods */
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Anh49Fachdaten getAnh49Fachdaten() {
        return this.anh49Fachdaten;
    }

    public void setAnh49Fachdaten(Anh49Fachdaten anh49Fachdaten) {
        this.anh49Fachdaten = anh49Fachdaten;
    }

    public Date getDatum() {
        return this.datum;
    }

    public void setDatum(Date datum) {
        this.datum = datum;
    }

    public String getMassnahme() {
        return this.massnahme;
    }

    public void setMassnahme(String massnahme) {
        this.massnahme = massnahme;
    }

    public String getSachbearbeiterIn() {
        return this.sachbearbeiterIn;
    }

    public void setSachbearbeiterIn(String sachbearbeiterIn) {
        this.sachbearbeiterIn = sachbearbeiterIn;
    }

    public Date getWiedervorlage() {
        return this.wiedervorlage;
    }

    public void setWiedervorlage(Date wiedervorlage) {
        this.wiedervorlage = wiedervorlage;
    }

    public Boolean getAbgeschlossen() {
        return this.abgeschlossen;
    }

    public void setAbgeschlossen(Boolean abgeschlossen) {
        this.abgeschlossen = abgeschlossen;
    }

    public boolean isEnabled() {
        return this.enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public boolean isDeleted() {
        return this.deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * To implement custom toString methods, jump to not generated code.<br>
     * Basically we either call on <code>toDebugString</code> for a debug
     * string, call on <code>toGuiString</code> for a gui representation or do
     * something completely different.
     * @return String
     */
    @Override
    public String toString() {
        return DatabaseClassToString.toStringForClass(this);
    }

    /**
     * Get a string representation for debugging
     * @return String
     */
    public String toDebugString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getSimpleName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("anh49Fachdaten").append("='").append(getAnh49Fachdaten()).append("' ");
        buffer.append("datum").append("='").append(getDatum()).append("' ");
        buffer.append("massnahme").append("='").append(getMassnahme()).append("' ");
        buffer.append("sachbearbeiterIn").append("='").append(getSachbearbeiterIn()).append("' ");
        buffer.append("wiedervorlage").append("='").append(getWiedervorlage()).append("' ");
        buffer.append("abgeschlossen").append("='").append(getAbgeschlossen()).append("' ");
        buffer.append("enabled").append("='").append(isEnabled()).append("' ");
        buffer.append("deleted").append("='").append(isDeleted()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }

    /**
     * @param other
     * @return <code>true</code>, if this and other are equal,
     *         <code>false</code> otherwise
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        if (other == null) return false;
        if (!(other instanceof Anh49Verwaltungsverf)) return false;
        return (this.getId().equals(
            ((Anh49Verwaltungsverf) other).getId()));
    }

    /**
     * Merge (save or update) a detached instance
     * @param detachedInstance the instance to merge
     * @return <code>Anh49Verwaltungsverf</code> the merged instance,
     *         if everything went okay,
     *         <code>null</code> otherwise
     */
    public static Anh49Verwaltungsverf merge(Anh49Verwaltungsverf detachedInstance) {
        log.debug("Merging Anh49Verwaltungsverf instance " + detachedInstance);
        return (Anh49Verwaltungsverf) new DatabaseAccess().merge(detachedInstance);
    }

    /**
     * Merge (save or update) this instance
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public boolean merge() {
        return (Anh49Verwaltungsverf.merge(this) != null);
    }

    /**
     * Delete (mark as deleted) a detached instance
     * @param detachedInstance the instance to delete
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public static boolean delete(Anh49Verwaltungsverf detachedInstance) {
        log.debug("Deleting Anh49Verwaltungsverf instance " + detachedInstance);
        return new DatabaseAccess().delete(detachedInstance);
    }

    /**
     * Delete (mark as deleted) this instance
     * @return <code>true</code>, if everything went okay,
     *         <code>false</code> otherwise
     */
    public boolean delete() {
        return Anh49Verwaltungsverf.delete(this);
    }

    /**
     * Find an <code>Anh49Verwaltungsverf</code> instance by its primary key
     * @param id the primary key value
     * @return <code>Anh49Verwaltungsverf</code> the requested instance,
     *         if one exists,
     *         <code>null</code> otherwise
     */
    public static Anh49Verwaltungsverf findById(java.lang.Integer id) {
        log.debug("Getting Anh49Verwaltungsverf instance with id: " + id);
        return (Anh49Verwaltungsverf)
            new DatabaseAccess().get(Anh49Verwaltungsverf.class, id);
    }

    /**
     * Get a list of all <code>Anh49Verwaltungsverf</code>
     * @return <code>List&lt;Anh49Verwaltungsverf&gt;</code>
     *         all <code>Anh49Verwaltungsverf</code>
     */
    public static List<Anh49Verwaltungsverf> getAll() {
        return DatabaseQuery.getAll(new Anh49Verwaltungsverf());
    }

    /* Custom code goes below here! */

}
