/**
 * Copyright 2005-2011, Stadt Bielefeld
 *
 * This file is part of AUIK (Anlagen- und Indirekteinleiter-Kataster).
 *
 * AUIK is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 2 of the License, or (at your
 * option) any later version.
 *
 * AUIK is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with AUIK. If not, see <http://www.gnu.org/licenses/>.
 *
 * AUIK has been developed by Stadt Bielefeld and Intevation GmbH.
 */
package de.bielefeld.umweltamt.aui.mappings.tipi;

import java.util.List;

import de.bielefeld.umweltamt.aui.utils.DatabaseAccess;

/**
 * DeaAdresse generated by hbm2java
 */
public class DeaAdresse  implements java.io.Serializable {

    private DeaAdresseId id;
    private String name1;
    private String name2;
    private String strasse;
    private String hausnr;
    private String plz;
    private String ort;
    private String staatskennung;

    public DeaAdresse() {
    }


    public DeaAdresse(DeaAdresseId id) {
        this.id = id;
    }

    public DeaAdresse(DeaAdresseId id, String name1, String name2, String strasse, String hausnr, String plz, String ort, String staatskennung) {
       this.id = id;
       this.name1 = name1;
       this.name2 = name2;
       this.strasse = strasse;
       this.hausnr = hausnr;
       this.plz = plz;
       this.ort = ort;
       this.staatskennung = staatskennung;
    }

    public DeaAdresseId getId() {
        return this.id;
    }

    public void setId(DeaAdresseId id) {
        this.id = id;
    }

    public String getName1() {
        return this.name1;
    }

    public void setName1(String name1) {
        this.name1 = name1;
    }

    public String getName2() {
        return this.name2;
    }

    public void setName2(String name2) {
        this.name2 = name2;
    }

    public String getStrasse() {
        return this.strasse;
    }

    public void setStrasse(String strasse) {
        this.strasse = strasse;
    }

    public String getHausnr() {
        return this.hausnr;
    }

    public void setHausnr(String hausnr) {
        this.hausnr = hausnr;
    }

    public String getPlz() {
        return this.plz;
    }

    public void setPlz(String plz) {
        this.plz = plz;
    }

    public String getOrt() {
        return this.ort;
    }

    public void setOrt(String ort) {
        this.ort = ort;
    }

    public String getStaatskennung() {
        return this.staatskennung;
    }

    public void setStaatskennung(String staatskennung) {
        this.staatskennung = staatskennung;
    }

    public static List<?> getDeaAdressen() {
        String query = "FROM DeaAdresse";
        return new DatabaseAccess().createQuery(query).list();
    }
}

