/**
 * Copyright 2005-2011, Stadt Bielefeld
 *
 * This file is part of AUIK (Anlagen- und Indirekteinleiter-Kataster).
 *
 * AUIK is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 2 of the License, or (at your
 * option) any later version.
 *
 * AUIK is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with AUIK. If not, see <http://www.gnu.org/licenses/>.
 *
 * AUIK has been developed by Stadt Bielefeld and Intevation GmbH.
 */
package de.bielefeld.umweltamt.aui.mappings.tipi;

import java.util.List;
import java.util.Calendar;

import de.bielefeld.umweltamt.aui.utils.DatabaseAccess;
import de.nrw.lds.tipi.inka.Inka_Betriebseinrichtung;

/**
 * InkaBetriebseinrichtung generated by hbm2java
 */
public class InkaBetriebseinrichtung  implements java.io.Serializable {

    private InkaBetriebseinrichtungId id;
    private Integer betriebNr;
    private Integer adresseBetreibNr;
    private Integer genehmigungNr;

    public InkaBetriebseinrichtung() {
    }

    public InkaBetriebseinrichtung(InkaBetriebseinrichtungId id) {
        this.id = id;
    }

    public InkaBetriebseinrichtung(InkaBetriebseinrichtungId id, Integer betriebNr, Integer adresseBetreibNr, Integer genehmigungNr) {
       this.id = id;
       this.betriebNr = betriebNr;
       this.adresseBetreibNr = adresseBetreibNr;
       this.genehmigungNr = genehmigungNr;
    }

    public InkaBetriebseinrichtungId getId() {
        return this.id;
    }

    public void setId(InkaBetriebseinrichtungId id) {
        this.id = id;
    }

    public Integer getBetriebNr() {
        return this.betriebNr;
    }

    public void setBetriebNr(Integer betriebNr) {
        this.betriebNr = betriebNr;
    }

    public Integer getAdresseBetreibNr() {
        return this.adresseBetreibNr;
    }

    public void setAdresseBetreibNr(Integer adresseBetreibNr) {
        this.adresseBetreibNr = adresseBetreibNr;
    }

    public Integer getGenehmigungNr() {
        return this.genehmigungNr;
    }

    public void setGenehmigungNr(Integer genehmigungNr) {
        this.genehmigungNr = genehmigungNr;
    }

    public static List<?> getInkaBetriebseinrichtungen() {
        String query = "FROM InkaBetriebseinrichtung";
        return new DatabaseAccess().createQuery(query).list();
    }

    public Inka_Betriebseinrichtung toServiceType() {
        // Ein default Änderungsdatum.
        Calendar aenderung = Calendar.getInstance();
        aenderung.set(2012, 1, 2);
        // Ein default Erfassungsdatum.
        Calendar erfassung = Calendar.getInstance();
        erfassung.set(2012, 1, 1);
        // Ein default Gültigkeits datum. (gültig_von)
        Calendar gueltig = Calendar.getInstance();
        gueltig.set(2012, 1, 1);

        Inka_Betriebseinrichtung item = new Inka_Betriebseinrichtung(
            aenderung,
            erfassung,
            Calendar.getInstance(), // Gültig bis aktuelles Datum.
            gueltig,
            true,
            this.getAdresseBetreibNr(), // Ersatzwert für nicht vorhandenes Feld 'adresse_anspr_nr'.
            1, // Default Wert für nicht vohandenes Feld 'adresse_anspr_ver'.
            this.getAdresseBetreibNr(),
            1,  // Default Wert für nicht vohandenes Feld 'adresse_betreib_ver'.
            null, // Default Wert für nicht vohandenes Feld 'arbeitsstaette_seq_nr'.
            1, // Default Wert für nicht vohandenes Feld 'arbeitsstaette_ver'.
            this.getBetriebNr(),
            1, // Default Wert für nicht vohandenes Feld 'betrieb_nr'.
            this.getId().getBetriebseinrichtungNr(),
            1, // Default Wert für nicht vohandenes Feld 'betriebseinrichtung_ver'.
            this.getGenehmigungNr(),
            1, // Default Wert für nicht vohandenes Feld 'genehmigung_ver'.
            null, // kein Datum, da stilllegung_jn = false.
            false, // Default für 'stillegung_jn'.
            "test", // Default für 'wz_code'.
            1 // Default für wz_code_ver.
        );
        return item;
    }
}

