/**
 * Copyright 2005-2011, Stadt Bielefeld
 *
 * This file is part of AUIK (Anlagen- und Indirekteinleiter-Kataster).
 *
 * AUIK is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 2 of the License, or (at your
 * option) any later version.
 *
 * AUIK is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with AUIK. If not, see <http://www.gnu.org/licenses/>.
 *
 * AUIK has been developed by Stadt Bielefeld and Intevation GmbH.
 */
package de.bielefeld.umweltamt.aui.mappings.tipi;

import java.util.List;

import de.bielefeld.umweltamt.aui.utils.DatabaseAccess;

/**
 * InkaBetriebseinrichtung generated by hbm2java
 */
public class InkaBetriebseinrichtung  implements java.io.Serializable {

    private InkaBetriebseinrichtungId id;
    private Integer betriebNr;
    private Integer adresseBetreibNr;
    private Integer genehmigungNr;

    public InkaBetriebseinrichtung() {
    }

    public InkaBetriebseinrichtung(InkaBetriebseinrichtungId id) {
        this.id = id;
    }

    public InkaBetriebseinrichtung(InkaBetriebseinrichtungId id, Integer betriebNr, Integer adresseBetreibNr, Integer genehmigungNr) {
       this.id = id;
       this.betriebNr = betriebNr;
       this.adresseBetreibNr = adresseBetreibNr;
       this.genehmigungNr = genehmigungNr;
    }

    public InkaBetriebseinrichtungId getId() {
        return this.id;
    }

    public void setId(InkaBetriebseinrichtungId id) {
        this.id = id;
    }

    public Integer getBetriebNr() {
        return this.betriebNr;
    }

    public void setBetriebNr(Integer betriebNr) {
        this.betriebNr = betriebNr;
    }

    public Integer getAdresseBetreibNr() {
        return this.adresseBetreibNr;
    }

    public void setAdresseBetreibNr(Integer adresseBetreibNr) {
        this.adresseBetreibNr = adresseBetreibNr;
    }

    public Integer getGenehmigungNr() {
        return this.genehmigungNr;
    }

    public void setGenehmigungNr(Integer genehmigungNr) {
        this.genehmigungNr = genehmigungNr;
    }

    public static List<?> getInkaBetriebseinrichtungen() {
        String query = "FROM InkaBetriebseinrichtung";
        return new DatabaseAccess().createQuery(query).list();
    }
}

