/**
 * Copyright 2005-2011, Stadt Bielefeld
 *
 * This file is part of AUIK (Anlagen- und Indirekteinleiter-Kataster).
 *
 * AUIK is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 2 of the License, or (at your
 * option) any later version.
 *
 * AUIK is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with AUIK. If not, see <http://www.gnu.org/licenses/>.
 *
 * AUIK has been developed by Stadt Bielefeld and Intevation GmbH.
 */
package de.bielefeld.umweltamt.aui.mappings.tipi;

import java.util.Calendar;
import java.util.Date;
import java.util.List;

import de.bielefeld.umweltamt.aui.utils.DatabaseAccess;
import de.nrw.lds.tipi.inka.Inka_Genehmigung;

/**
 * InkaGenehmigung generated by hbm2java
 */
public class InkaGenehmigung  implements java.io.Serializable {
    private static final long serialVersionUID = -6739768235170046107L;

    private InkaGenehmigungId id;
    private Integer betriebNr;
    private String behoerdenId;
    private Date genehmigungDatum;
    private String befristetIn;

    public InkaGenehmigung() {
    }

    public InkaGenehmigung(InkaGenehmigungId id) {
        this.id = id;
    }

    public InkaGenehmigung(InkaGenehmigungId id, Integer betriebNr, String behoerdenId, Date genehmigungDatum, String befristetIn) {
       this.id = id;
       this.betriebNr = betriebNr;
       this.behoerdenId = behoerdenId;
       this.genehmigungDatum = genehmigungDatum;
       this.befristetIn = befristetIn;
    }

    public InkaGenehmigungId getId() {
        return this.id;
    }

    public void setId(InkaGenehmigungId id) {
        this.id = id;
    }

    public Integer getBetriebNr() {
        return this.betriebNr;
    }

    public void setBetriebNr(Integer betriebNr) {
        this.betriebNr = betriebNr;
    }

    public String getBehoerdenId() {
        return this.behoerdenId;
    }

    public void setBehoerdenId(String behoerdenId) {
        this.behoerdenId = behoerdenId;
    }

    public Date getGenehmigungDatum() {
        return this.genehmigungDatum;
    }

    public void setGenehmigungDatum(Date genehmigungDatum) {
        this.genehmigungDatum = genehmigungDatum;
    }

    public String getBefristetIn() {
        return this.befristetIn;
    }

    public void setBefristetIn(String befristetIn) {
        this.befristetIn = befristetIn;
    }

    public static List<?> getInkaGenehmigungen() {
        String query = "FROM InkaGenehmigung";
        return new DatabaseAccess().createQuery(query).list();
    }

    public Inka_Genehmigung toServiceType() {
        // Ein default Änderungsdatum.
        Calendar aenderung = Calendar.getInstance();
        aenderung.set(2012, 1, 2);
        // Ein default Erfassungsdatum.
        Calendar erfassung = Calendar.getInstance();
        erfassung.set(2012, 1, 1);
        // Ein default Gültigkeits datum. (gültig_von)
        Calendar gueltig = Calendar.getInstance();
        gueltig.set(2012, 1, 1);

        Calendar date = Calendar.getInstance();
        if (this.getGenehmigungDatum() != null) {
            date.setTime(this.getGenehmigungDatum());
        }
        else {
            date = null;
        }

        Inka_Genehmigung item = new Inka_Genehmigung(
            aenderung,
            erfassung,
            Calendar.getInstance(), // Gültig bis aktuelles Datum.
            gueltig,
            true,
            null, // Defaultwert, da 'befristet_jn' auf false gesetzt ist
            false, // Default Wert für nicht vohandenes Feld 'befristet_jn'.
            this.getBehoerdenId(),
            1,  // Default Wert für nicht vohandenes Feld 'behoerden_ver'.
            this.getBetriebNr(),
            1, // Default Wert für nicht vohandenes Feld 'betrieb_ver'.
            date,
            this.getId().getGenehmigungNr(),
            1 // Default Wert für nicht vohandenes Feld 'genehmigung_ver'
        );
        return item;
    }


}

