/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Jan 20 17:02:28 CET 2005 by MyEclipse Hibernate Tool.
 */
package de.bielefeld.umweltamt.aui.mappings.vaws;

import java.io.Serializable;

/**
 * A class that represents a row in the VAWS_STANDORTGGHWSG table. 
 * You can customize the behavior of this class by editing the class, {@link VawsStandortgghwsg}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized 
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractVawsStandortgghwsg 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer standortggid;

    /** The value of the simple standortgg property. */
    private java.lang.String standortgg;

    /**
     * Simple constructor of AbstractVawsStandortgghwsg instances.
     */
    public AbstractVawsStandortgghwsg()
    {
    }

    /**
     * Constructor of AbstractVawsStandortgghwsg instances given a simple primary key.
     * @param standortggid
     */
    public AbstractVawsStandortgghwsg(java.lang.Integer standortggid)
    {
        this.setStandortggid(standortggid);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getStandortggid()
    {
        return standortggid;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param standortggid
     */
    public void setStandortggid(java.lang.Integer standortggid)
    {
        this.hashValue = 0;
        this.standortggid = standortggid;
    }

    /**
     * Return the value of the STANDORTGG column.
     * @return java.lang.String
     */
    public java.lang.String getStandortgg()
    {
        return this.standortgg;
    }

    /**
     * Set the value of the STANDORTGG column.
     * @param standortgg
     */
    public void setStandortgg(java.lang.String standortgg)
    {
        this.standortgg = standortgg;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof VawsStandortgghwsg))
            return false;
        VawsStandortgghwsg that = (VawsStandortgghwsg) rhs;
        if (this.getStandortggid() != null && that.getStandortggid() != null)
        {
            if (! this.getStandortggid().equals(that.getStandortggid()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int standortggidValue = this.getStandortggid() == null ? 0 : this.getStandortggid().hashCode();
            result = result * 37 + standortggidValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
